package dev.graphnous.application.authorization;

public enum Permission {
    SYSTEM_CREATE,
    SYSTEM_READ,
    SYSTEM_UPDATE,
    SYSTEM_DELETE,

    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    SCAN_READ, SCAN_CREATE, SCAN_DELETE, PROJECT_DELETE,

    NOTIFICATION_CREATE,
    NOTIFICATION_READ,
    NOTIFICATION_UPDATE,
    NOTIFICATION_DELETE,

    CHAT_READ,
    CHAT_WRITE,
    CHAT_DELETE
}
