import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ToastProvider } from "graphnous-theme";

import { AppLinkProvider } from "@/components/AppLinkProvider";
import { ApiClientProvider } from "@/lib/api/client";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ApiClientProvider>
          <AppLinkProvider>
            <ToastProvider>{children}</ToastProvider>
          </AppLinkProvider>
        </ApiClientProvider>
      </body>
    </html>
  );
}
